using System.Text.Json.Serialization;

#nullable disable

namespace Stigma.Tools.ProtocolBuilder.Options;

public sealed class GlobalOptions
{
    public PathOptions Paths { get; set; }

    public string Namespace { get; set; }

    [JsonIgnore]
    public string Signature =>
        $"""
         /*
         * This file is automatically generated by {typeof(Program).Assembly.GetName().Name}
         * Do not modify it manually
         *
         * Generated at {DateTime.Now:dd/MM/yyyy HH:mm:ss}
         */
         """;
}