/*
* This file is automatically generated by Stigma.Tools.ProtocolBuilder
* Do not modify it manually
*
* Generated at 29/07/2024 22:52:03
*/

namespace Stigma.Protocol.Enums;

public enum AlignmentSides
{
	AlignmentUnknown = -2,
	AlignmentWithout = -1,
	AlignmentNeutral = 0,
	AlignmentAngel = 1,
	AlignmentEvil = 2,
	AlignmentMercenary = 3
}
