/*
 * This file is automatically generated by Stigma.Tools.ProtocolBuilder
 * Do not modify it manually
 *
 * Generated at 29/07/2024 22:52:03
 */

namespace Stigma.Protocol.Enums;

public enum ChatErrors
{
    ChatErrorUnknown = 0,
    ChatErrorReceiverNotFound = 1,
    ChatErrorInteriorMonologue = 2,
    ChatErrorNoGuild = 3,
    ChatErrorNoParty = 4,
    ChatErrorAlign = 5,
    ChatErrorInvalidMap = 6
}