/*
* This file is automatically generated by Stigma.Tools.ProtocolBuilder
* Do not modify it manually
*
* Generated at 29/07/2024 22:52:03
*/

namespace Stigma.Protocol.Enums;

public enum ChatChannelsMultis
{
	ChannelGlobal = 0,
	ChannelTeam = 1,
	ChannelGuild = 2,
	ChannelAlign = 3,
	ChannelParty = 4,
	ChannelSales = 5,
	ChannelSeek = 6,
	ChannelNoob = 7,
	ChannelAdmin = 8
}
