/*
 * This file is automatically generated by Stigma.Tools.ProtocolBuilder
 * Do not modify it manually
 *
 * Generated at 29/07/2024 22:52:03
 */

namespace Stigma.Protocol.Enums;

public enum CompassTypes
{
    CompassTypeSimple = 0,
    CompassTypeSpouse = 1,
    CompassTypeParty = 2,
    CompassTypePvpSeek = 3
}