/*
* This file is automatically generated by Stigma.Tools.ProtocolBuilder
* Do not modify it manually
*
* Generated at 29/07/2024 22:52:03
*/

namespace Stigma.Protocol.Enums;

public enum CrafterDirectoryParamBits
{
	CraftOptionNone = 0,
	CraftOptionNotFree = 1,
	CraftOptionNotFreeExceptOnFail = 2,
	CraftOptionResourcesRequired = 4
}
