/*
* This file is automatically generated by Stigma.Tools.ProtocolBuilder
* Do not modify it manually
*
* Generated at 29/07/2024 22:52:03
*/

namespace Stigma.Protocol.Enums;

public enum DebugLevels
{
	LevelTrace = 0,
	LevelDebug = 1,
	LevelInfo = 2,
	LevelWarn = 3,
	LevelError = 4,
	LevelFatal = 5
}
