/*
* This file is automatically generated by Stigma.Tools.ProtocolBuilder
* Do not modify it manually
*
* Generated at 29/07/2024 22:52:03
*/

namespace Stigma.Protocol.Enums;

public enum ExchangeTypes
{
	NpcShop = 0,
	PlayerTrade = 1,
	NpcTrade = 2,
	Craft = 3,
	DisconnectedVendor = 4,
	Storage = 5,
	ShopStock = 6,
	Taxcollector = 8,
	NpcModifyTrade = 9,
	BidhouseSell = 10,
	BidhouseBuy = 11,
	MulticraftCrafter = 12,
	MulticraftCustomer = 13,
	JobIndex = 14,
	Mount = 15,
	MountStable = 16,
	NpcResurectPet = 17,
	NpcTradeMount = 18
}
