/*
* This file is automatically generated by Stigma.Tools.ProtocolBuilder
* Do not modify it manually
*
* Generated at 29/07/2024 22:52:03
*/

namespace Stigma.Protocol.Enums;

public enum ExchangeErrors
{
	RequestImpossible = 1,
	RequestCharacterOccupied = 2,
	RequestCharacterJobNotEquiped = 3,
	RequestCharacterToolTooFar = 4,
	RequestCharacterOverloaded = 5,
	RequestCharacterNotSuscriber = 6,
	BuyError = 7,
	SellError = 8,
	MountPaddockError = 9,
	BidSearchError = 10
}
