/*
* This file is automatically generated by Stigma.Tools.ProtocolBuilder
* Do not modify it manually
*
* Generated at 29/07/2024 22:52:03
*/

namespace Stigma.Protocol.Enums;

public enum FightOutcomes
{
	ResultLost = 0,
	ResultDraw = 1,
	ResultVictory = 2,
	ResultTax = 5,
	ResultDefenderGroup = 6
}
