/*
* This file is automatically generated by Stigma.Tools.ProtocolBuilder
* Do not modify it manually
*
* Generated at 29/07/2024 22:52:03
*/

namespace Stigma.Protocol.Enums;

public enum FightTypes
{
	FightTypeChallenge = 0,
	FightTypeAgression = 1,
	FightTypePvma = 2,
	FightTypeMxvm = 3,
	FightTypePvm = 4,
	FightTypePvt = 5,
	FightTypePvmu = 6
}
