/*
 * This file is automatically generated by Stigma.Tools.ProtocolBuilder
 * Do not modify it manually
 *
 * Generated at 29/07/2024 22:52:03
 */

namespace Stigma.Protocol.Enums;

public enum FighterRefusedReasons
{
    FighterAccepted = 0,
    ChallengeFull = 1,
    TeamFull = 2,
    WrongAlignment = 3,
    WrongGuild = 4,
    TooLate = 5,
    MutantRefused = 6,
    WrongMap = 7,
    JustRespawned = 8,
    ImOccupied = 9,
    OpponentOccupied = 10,
    FightMyself = 11,
    InsufficientRights = 12,
    MemberAccountNeeded = 13,
    OpponentNotMember = 14,
    TeamLimitedByMaincharacter = 15,
    MultiaccountNotAllowed = 16,
    GhostRefused = 17
}