/*
 * This file is automatically generated by Stigma.Tools.ProtocolBuilder
 * Do not modify it manually
 *
 * Generated at 29/07/2024 22:52:03
 */

namespace Stigma.Protocol.Enums;

public enum GuildCreationResults
{
    GuildCreateOk = 1,
    GuildCreateErrorNameInvalid = 2,
    GuildCreateErrorAlreadyInGuild = 3,
    GuildCreateErrorNameAlreadyExists = 4,
    GuildCreateErrorEmblemAlreadyExists = 5,
    GuildCreateErrorLeave = 6,
    GuildCreateErrorCancel = 7,
    GuildCreateErrorRequirementUnmet = 8
}