/*
 * This file is automatically generated by Stigma.Tools.ProtocolBuilder
 * Do not modify it manually
 *
 * Generated at 29/07/2024 22:52:03
 */

namespace Stigma.Protocol.Enums;

public enum GuildInformationsTypes
{
    InfoGeneral = 1,
    InfoMembers = 2,
    InfoBoosts = 3,
    InfoPaddocks = 4,
    InfoHouses = 5,
    InfoTaxCollector = 6,
    InfoTaxCollectorLeave = 7
}