/*
* This file is automatically generated by Stigma.Tools.ProtocolBuilder
* Do not modify it manually
*
* Generated at 29/07/2024 22:52:03
*/

namespace Stigma.Protocol.Enums;

public enum ListAddFailures
{
	ListAddFailureUnknown = 0,
	ListAddFailureOverQuota = 1,
	ListAddFailureNotFound = 2,
	ListAddFailureEgocentric = 3,
	ListAddFailureIsDouble = 4
}
