/*
 * This file is automatically generated by Stigma.Tools.ProtocolBuilder
 * Do not modify it manually
 *
 * Generated at 29/07/2024 22:52:03
 */

namespace Stigma.Protocol.Enums;

public enum NicknameErrors
{
    AlreadyUsed = 1,
    SameAsLogin = 2,
    TooSimilarToLogin = 3,
    InvalidNick = 4,
    UnknownNickError = 99
}