/*
* This file is automatically generated by Stigma.Tools.ProtocolBuilder
* Do not modify it manually
*
* Generated at 29/07/2024 22:52:03
*/

namespace Stigma.Protocol.Enums;

public enum NumericalValueTypes
{
	NumericalValueDefault = 0,
	NumericalValueCollect = 1,
	NumericalValueCraft = 2,
	NumericalValuePaddock = 3,
	NumericalValueRed = 64,
	NumericalValueBlue = 65,
	NumericalValueGreen = 66
}
