/*
 * This file is automatically generated by Stigma.Tools.ProtocolBuilder
 * Do not modify it manually
 *
 * Generated at 29/07/2024 22:52:03
 */

namespace Stigma.Protocol.Enums;

public enum PartyJoinErrors
{
    PartyJoinErrorUnknown = 0,
    PartyJoinErrorPlayerNotFound = 1,
    PartyJoinErrorPartyNotFound = 2,
    PartyJoinErrorPartyFull = 3,
    PartyJoinErrorPlayerBusy = 4,
    PartyJoinErrorPlayerIsAlreadyBeingInvited = 5,
    PartyJoinErrorPlayerAlreadyInAParty = 6
}