/*
 * This file is automatically generated by Stigma.Tools.ProtocolBuilder
 * Do not modify it manually
 *
 * Generated at 29/07/2024 22:52:03
 */

namespace Stigma.Protocol.Enums;

public enum ServerConnectionErrors
{
    ServerConnectionErrorDueToStatus = 0,
    ServerConnectionErrorNoReason = 1,
    ServerConnectionErrorAccountRestricted = 2,
    ServerConnectionErrorCommunityRestricted = 3,
    ServerConnectionErrorLocationRestricted = 4,
    ServerConnectionErrorSubscribersOnly = 5,
    ServerConnectionErrorRegularPlayersOnly = 6
}