/*
* This file is automatically generated by Stigma.Tools.ProtocolBuilder
* Do not modify it manually
*
* Generated at 29/07/2024 22:52:03
*/

namespace Stigma.Protocol.Enums;

public enum ServerStatuses
{
	StatusUnknown = 0,
	Offline = 1,
	Starting = 2,
	Online = 3,
	Nojoin = 4,
	Saving = 5,
	Stoping = 6,
	Full = 7
}
