/*
 * This file is automatically generated by Stigma.Tools.ProtocolBuilder
 * Do not modify it manually
 *
 * Generated at 29/07/2024 22:52:03
 */

namespace Stigma.Protocol.Enums;

public enum SocialContactCategories
{
    SocialContactFriend = 0,
    SocialContactSpouse = 1,
    SocialContactParty = 2,
    SocialContactGuild = 3,
    SocialContactCrafter = 4
}