/*
 * This file is automatically generated by Stigma.Tools.ProtocolBuilder
 * Do not modify it manually
 *
 * Generated at 29/07/2024 22:52:03
 */

namespace Stigma.Protocol.Enums;

public enum SubEntityBindingPointCategories
{
    HookPointCategoryUnused = 0,
    HookPointCategoryPet = 1,
    HookPointCategoryMountDriver = 2,
    HookPointCategoryLiftedEntity = 3,
    HookPointCategoryBaseBackground = 4,
    HookPointCategoryMerchantBag = 5,
    HookPointCategoryBaseForeground = 6
}