/*
 * This file is automatically generated by Stigma.Tools.ProtocolBuilder
 * Do not modify it manually
 *
 * Generated at 29/07/2024 22:52:03
 */

namespace Stigma.Protocol.Enums;

public enum SubscriptionRequireds
{
    LimitedToSubscriber = 0,
    LimitOnJobXp = 1,
    LimitOnJobUse = 2,
    LimitOnMap = 3,
    LimitOnItem = 4,
    LimitOnVendor = 5
}