/*
* This file is automatically generated by Stigma.Tools.ProtocolBuilder
* Do not modify it manually
*
* Generated at 29/07/2024 22:52:03
*/

namespace Stigma.Protocol.Enums;

public enum TaxCollectorErrorReasons
{
	TaxCollectorErrorUnknown = 0,
	TaxCollectorNotFound = 1,
	TaxCollectorNotOwned = 2,
	TaxCollectorNoRights = 3,
	TaxCollectorMaxReached = 4,
	TaxCollectorAlreadyOne = 5,
	TaxCollectorCantHireYet = 6,
	TaxCollectorCantHireHere = 7,
	TaxCollectorNotEnoughKamas = 8
}
