/*
* This file is automatically generated by Stigma.Tools.ProtocolBuilder
* Do not modify it manually
*
* Generated at 29/07/2024 22:52:03
*/

namespace Stigma.Protocol.Enums;

public enum TextInformationTypes
{
	TextInformationMessage = 0,
	TextInformationError = 1,
	TextInformationPvp = 2,
	TextInformationFightLog = 3,
	TextInformationPopup = 4,
	TextLivingObject = 5,
	TextEntityTalk = 6
}
